# Generated by Django 2.1 on 2018-08-03 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=False, max_length=50)),
                ('photo', models.ImageField(help_text='Photo of cookie', upload_to='profile_photo')),
                ('speciality', models.TextField(default=False)),
                ('price', models.FloatField(default=False)),
                ('avg_rating', models.FloatField(default=0)),
                ('no_of_review', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(default='Anonymous', max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('review', models.TextField(verbose_name=False)),
                ('rating', models.IntegerField()),
                ('review_type', models.BooleanField()),
                ('item', models.ForeignKey(on_delete=None, to='review_classifier.Item')),
            ],
        ),
    ]
