# Generated by Django 2.1 on 2018-08-05 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_classifier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Old_Traing_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('review_type', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Training_Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(default='Anonymous', max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('review', models.TextField()),
                ('rating', models.IntegerField()),
                ('review_type', models.BooleanField()),
                ('item', models.ForeignKey(on_delete=None, to='review_classifier.Item')),
            ],
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(),
        ),
    ]
