# Generated by Django 2.1 on 2018-08-05 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_classifier', '0002_auto_20180805_1355'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Old_Traing_data',
            new_name='Old_Training_data',
        ),
    ]
