# Generated by Django 2.1 on 2018-12-10 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_classifier', '0004_auto_20180806_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(default=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='customer_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='item',
            field=models.ForeignKey(null=True, on_delete=None, to='review_classifier.Item'),
        ),
        migrations.AlterField(
            model_name='training_review',
            name='customer_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
