# Generated by Django 2.1 on 2018-12-10 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_classifier', '0005_auto_20181210_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='is_verified',
            field=models.BooleanField(null=True),
        ),
    ]
